version: '2'
services:
  app:
    container_name: wms_app
    hostname: app
    image: mytinywms/mytinywms
    build:
      context: .
    links:
    - db
    - redis
    environment:
    - APP_NAME="myTinyWMS"
    - APP_ENV=local
    - APP_DEBUG=true
    - DEBUGBAR_ENABLED=false
    - APP_DEMO=false
    - APP_KEY=base64:sgppryzAzGfrijoL5hW5a6CxXO/95IlYasKP7wDT3RE=
    - APP_URL=http://localhost/
    - LOGO_PATH=
    - HORIZON_NOTIFICATION_RECEIVER=
    - INVENTORY_MANUAL_RECEIVER=
    - INVENTORY_AUTOMATIC_RECEIVER=
    - DB_HOST=db
    - DB_PORT=3306
    - DB_DATABASE=mss_test
    - DB_USERNAME=root
    - DB_PASSWORD=mss
    - QUEUE_DRIVER=sync
    - CACHE_DRIVER=array
    - SESSION_DRIVER=redis
    - REDIS_HOST=redis
    - REDIS_PASSWORD=null
    - REDIS_PORT=6379
    - MAIL_DRIVER=smtp
    - MAIL_HOST=
    - MAIL_PORT=
    - MAIL_USERNAME=
    - MAIL_PASSWORD=
    - MAIL_ENCRYPTION=
    - MAIL_FROM_ADDRESS=
    - MAIL_FROM_NAME=
    - IMAP_HOST=
    - IMAP_PORT=
    - IMAP_ENCRYPTION=
    - IMAP_USERNAME=
    - IMAP_PASSWORD=
    - AUTH_DRIVER=eloquent
    volumes
    - ./data/screenshots:/data/www/tests/Browser/screenshots
    - ./data/storage:/data/www/storage
    - ./data/cache:/data/www/bootstrap/cache

  db:
    container_name: wms_db
    image: mariadb:10.2
    environment:
    - MYSQL_DATABASE=mss_test
    - MYSQL_ROOT_PASSWORD=mss
    - MYSQL_USER=mss
    - MYSQL_PASSWORD=mss
    volumes:
    - ./data/db:/var/lib/mysql

  redis:
    container_name: wms_redis
    image: redis

  selenium:
    container_name: mss_selenium
    image: robcherry/docker-chromedriver
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      CHROMEDRIVER_PORT: "4444"
    depends_on:
      - app
    links:
      - app:mss.test
    volumes:
      - /dev/shm:/dev/shm
    cap_add:
      - "SYS_ADMIN"
